import 'package:flutter/material.dart';

class List1Page extends StatefulWidget {
  @override
  _List1PageState createState() => _List1PageState();
}

class _List1PageState extends State<List1Page> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text("List 1"),
      ),
      body: ListView(
        scrollDirection: Axis.vertical,
        reverse: true,
        children: <Widget>[
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
          new Text('aaaaaaaa'),
          new Text('bbbbbbb'),
          new Text('cccccccccccc'),
          new Text('dddddddddddd'),
          new Text('eeeeeeeeeeeee'),
          new Text('ggggggggggggg'),
          new Text('wwwwwwwwwwww'),
          new Text('hhhhhhhhhhhh'),
          new Text('jjjjjjjjjjjjjjj'),
        ],
      ),
    );
  }
}
